baseURL = 'https://entitypumps.com/'
languageCode = 'en-gb'
title = 'Entity Pumps by Entity Hydrodynamics'
theme = 'agnes'
publishDir = "docs"

[params]
	dateFormat = "Jan 2, 2023"
	authorName = "Entity Hydrodynamics"
	google_analytics_id = "GA-"

# [menu]
# 	[[menu.main]]
# 		Name = "Contact"
# 		URL = "#"
# 		weight = 1

# 	[[menu.main]]
# 		Name = "About us"
# 		URL = "#"
# 		weight = 2

# 	[[menu.main]]
# 		Name = "FAQ's"
# 		URL = "#"
# 		weight = 3

# 	[[menu.main]]
# 		Name = "Support"
# 		URL = "#"
# 		weight = 4

# [params.social]
# 	TwitterURL = "https://twitter.com/podbharati"
# 	GoogleURL = "http://google.com"
# 	FacebookURL = "https://facebook.com/podbharati"

[params.content]
	LeadTitle = "Top Quality Centrifugal Pumps for your project"
	HeroImage = "images/hero-image.png"
	LeadDescription1 = "Entity Hydrodynamics has been serving over 500 businesses — in India and overseas — for 25+ years."
	LeadDescription2 = "We offer end-to-end services: right from pump design, manufacturing, testing, and installation to match your project's requirements."
	ButtonCaption = "Email for a Free Consultation"
	ButtonURL = "mailto:inbox@entitypumps.com"
	FooterButtonCaption = "Email for Product Catalog"

[[params.feature]]
	FeatureTitle = "Self-aligned flange-mounted pumps"
	FeatureDescription = "Ideal for handling aggressive and explosive liquids such as chlorides, dyes, sulphides, alkalis, and phosphates."
	FeatureImage = "images/self-aligned-flange-mounted-pumps.png"

[[params.feature]]
	FeatureTitle = "Non-clog pumps"
	FeatureDescription = "Ideal for pumping slurries or liquids containing fibrous material."
	FeatureImage = "images/non-clog-pumps.png"

[[params.feature]]
	FeatureTitle = "Self-priming pumps"
	FeatureDescription = "Pumps muddy water, sea water, effluents, and solvents."
	FeatureImage = "images/self-priming-pumps.png"

[[params.feature]]
	FeatureTitle = "Air-cooled thermic fluid pumps"
	FeatureDescription = "Designed to withstand all kinds of heat transfer fluids over 100°C."
	FeatureImage = "images/air-cooled-thermic-fluid-pumps.png"

[[params.feature]]
	FeatureTitle = "Submerged non-clog pumps"
	FeatureDescription = "For handling sewage, slurry, viscous liquids, unscreened juice, and textile slurries."
	FeatureImage = "images/submerged-non-clog-pumps.png"

[[params.feature]]
	FeatureTitle = "Submerged steam-jacketed pumps"
	FeatureDescription = "Carries fluids that solidify at ambient temperature and must be heated in transit, e.g. molten sulfur, sulfur trioxide (SO₃)."
	FeatureImage = "images/submerged-steam-jacketed-pumps.png"

[[params.feature]]
	FeatureTitle = "Submerged multi-stage pumps"
	FeatureDescription = "Specially designed to give exceptionally high pressure heads."
	FeatureImage = "images/submerged-multistage-pumps.png"

[[params.feature]]
	FeatureTitle = "Floor-mounted multi-stage pumps"
	FeatureDescription = "Widely used to handle clean and contaminated water, scrubber water, and light chemicals."
	FeatureImage = "images/floor-mounted-multistage-pumps.png"

[[params.choice]]
	Title = "Reasonable pricing"
	Description1 = "Our 500+ customers trust us to provide top-quality at the right price!"
	Description2 = "We are in it together for the long run and want to do our best to see you and your projects succeed."

[[params.choice]]
	Title = "High quality standards"
	Description1 = "We have a strict in-house Quality Control process. Nothing leaves our shop without an approved test certificate."
	Description2 = "This has earned us stamps of approval from the likes of Department of Atomic Energy, ISRO, NTPC."

[[params.choice]]
	Title = "One-stop-shop"
	Description1 = "We have designed and developed more than 100 models of Centrifugal Pumps, for a variety of industries, in various materials of constructions."
	Description2 = "You can count on us for timely after-sales service and spares."

[[params.about]]
	Title = "Ganesh Shridhar Kulkarni"
	Description1 = "Mr. Kulkarni founded Entity Hydrodynamics in 1996, and leads the team with his 40+ years of experience in the pump manufacturing industry."
	Description2 = "He is a well-respected leader and mentor of our team. And, will bring all his experience as an expert Pump Designer and Manufacturer to bear on any orders we undertake."

[[params.about]]
	Title = "Vijay Mohan Jalihal"
	Description1 = "Mr. Jalihal is involved in pump and mechanical transmission industry since 1988, first as DGM of Kirloskar Ebara Pumps and then as MD of KTR Couplings' India manufacturing unit."
	Description2 = "His experience with Quality Control and Project Execution helps us deliver top-quality products, on time."

[[params.about]]
	Title = "Vinay Mukesh Patel"
	Description1 = "Vinay has had a successful career in Information Technology since 2009, during which he as worked with clients of all sizes across the globe, on high-stakes projects."
	Description2 = "He experience helps us push our Global Marketing and Sales efforts and ensure that our Customers have a delightful experience – every single time!"
